export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SUCCESS_SEARCH_MOVIE = 'SUCCESS_SEARCH_MOVIE';
export const ERROR_SEARCH_MOVIE = 'ERROR_SEARCH_MOVIE';
export const CLEAR_MOVIE = 'CLEAR_MOVIE';